### ISSUE TITLE
Route history with ID

### ISSUE THREAD

**Issue by timjcook** [4lex-io/ember-route-history#2]
Currently I can't set an ID in the history, so I can't return to routes that require an ID. I'm thinking that each history item could be an object 

``` javascript
{
  routeName: "user",
  id: 10
}
```

rather than just a routeName, then I could return to that route with the right ID and maintain state.

**Comment by alexmngn** [comment]
Hey,
I don't really have the time to implement this right now but feel free to send me a pull request with the improvement!

**Comment by timjcook** [comment]
Sent one through, let me know what you think.
