### ISSUE TITLE
The initializer `store` has been deprecated. 

### ISSUE THREAD

**Issue by localpcguy** [4lex-io/ember-route-history#7]
> The initializer `store` has been deprecated. Please update your `injectRouteHistory` initializer to use use `after: 'ember-data'` instead. 

See https://www.emberjs.com/deprecations/ember-data/v2.x/#toc_id-ds-deprecated-initializers

Looks like a PR has already been submitted for this: #6

**Comment by sandstrom** [comment]
Can this issue be closed? @localpcguy (looks like this is fixed)

**Comment by localpcguy** [comment]
Yup, looks like #6 fixed it when it was merged
